//
//  StorageConfigConstants.h
//  Upster
//
//  Created by Sunnyke on 15/12/17.
//  Copyright © 2015年 oceanwing. All rights reserved.
//

#ifndef StorageConfigConstants_h
#define StorageConfigConstants_h

#define STORAGE_CONFIG_TOKEN @"STORAGE_CONFIG_TOKEN"
#define STORAGE_CONFIG_USER_ID @"STORAGE_CONFIG_USER_ID"
#define STORAGE_CONFIG_PASSWORD @"STORAGE_CONFIG_PASSWORD"
#define STORAGE_CONFIG_USER_INFO @"STORAGE_CONFIG_USER_INFO"

#define STORAGE_MODEL_LOGIN @"STORAGE_MODEL_LOGIN"
#define STORAGE_ACCOUNT_EMAIL @"STORAGE_ACCOUNT_EMAIL"
#define STORAGE_IS_LOGIN @"STORAGE_IS_LOGIN"

#define STORAGE_ACCOUNT_EMAIL @"STORAGE_ACCOUNT_EMAIL"
#define STORAGE_LOGIN_TOKEN @"STORAGE_LOGIN_TOKEN"

#define STORAGE_SECRET_CODE @"STORAGE_SECRET_CODE"

#define STORAGE_PERIPHERAL_NAME @"STORAGE_PERIPHERAL_NAME"

#define STORAGE_TEMPERATURE_UNIT @"STORAGE_TEMPERATURE_UNIT"

#define STORAGE_SELECT_DEVICEMAC @"STORAGE_SELECT_DEVICEMAC"

#define STORAGE_SYSTEM_LANGUAGE @"STORAGE_SYSTEM_LANGUAGE"

#define STORAGE_LONGIN_CLIENT @"STORAGE_LONGIN_CLIENT"

#define STORAGE_PUSH_BADGE @"STORAGE_PUSH_BADGE"

#define STORAGE_SYNC_TIME @"STORAGE_SYNC_TIME"

#define SERVER_DATA_INDEX @"SERVER_DATA_INDEX"

#define STORAGE_LOCALE_PUSH_TIME @"STORAGE_LOCALE_PUSH_TIME"

#define STORAGE_DEVICE_LIST @"STORAGE_DEVICE_LIST"

#define STORAGE_HOME_PUSH_LIST @"STORAGE_HOME_PUSH_LIST"

#endif /* StorageConfigConstants_h */
